// Comprehensive offshore services data from offshore.cat scraper
const servicesData = [
    // RECOMMENDED SERVICES (Premium)
    {
        id: 1,
        name: "ALUY",
        website: "p.ol.uy",
        description: "Hosting without compromises.",
        category: "recommended",
        company: "ALUY Hosting",
        country: "uy",
        logPolicy: "Requires email confirmation",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Crypto", "Credit Card", "PayPal", "Cash"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    {
        id: 2,
        name: "PrivateAlps",
        website: "privatealps.net",
        description: "Your one and only destination for true offshore hosting services, powered by an ethical team of professionals",
        category: "recommended",
        company: "PrivateAlps AG",
        country: "ch",
        logPolicy: "Requires email confirmation",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Crypto", "Credit Card", "Apple Pay"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    {
        id: 3,
        name: "ProtonMail",
        website: "protonmail.com",
        description: "Secure email service with end-to-end encryption and privacy-focused features.",
        category: "recommended",
        company: "Proton Technologies AG",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    {
        id: 4,
        name: "Signal",
        website: "signal.org",
        description: "Privacy-focused messaging app with advanced encryption features.",
        category: "recommended",
        company: "Signal Foundation",
        country: "us",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Donations"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    {
        id: 5,
        name: "Mullvad",
        website: "mullvad.net",
        description: "Privacy-focused VPN with anonymous accounts and no personal data collection.",
        category: "recommended",
        company: "Mullvad VPN AB",
        country: "se",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Crypto", "Cash", "Credit Card"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    {
        id: 6,
        name: "Librem 5",
        website: "puri.sm",
        description: "Security-focused smartphone with hardware kill switches.",
        category: "recommended",
        company: "Purism",
        country: "us",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Crypto"],
        status: "premium",
        lastChange: "2025-01-29"
    },

    // HOSTING SERVICES (From offshore.cat scraper)
    {
        id: 101,
        name: "BitLaunch",
        website: "bitlaunch.io",
        description: "Create VPS in seconds, using crypto",
        category: "hosting",
        company: "BitLaunch Ltd",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes & No",
        paymentMethods: ["Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 102,
        name: "Cockbox",
        website: "cockbox.org",
        description: "Owned by Vincent Canfield, current administrator of cock.li email service",
        category: "hosting",
        company: "Cockbox Hosting",
        country: "cw",
        logPolicy: "Requires email confirmation",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 103,
        name: "Hostinger",
        website: "hostinger.com",
        description: "Affordable web hosting with excellent performance and 24/7 customer support.",
        category: "hosting",
        company: "Hostinger International",
        country: "lt",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 104,
        name: "DigitalOcean",
        website: "digitalocean.com",
        description: "Cloud infrastructure provider with simple pricing and developer-friendly tools.",
        category: "hosting",
        company: "DigitalOcean Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 105,
        name: "Vultr",
        website: "vultr.com",
        description: "High-performance cloud infrastructure with global data centers.",
        category: "hosting",
        company: "Vultr Holdings",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 106,
        name: "Linode",
        website: "linode.com",
        description: "Cloud hosting provider with developer-friendly tools and competitive pricing.",
        category: "hosting",
        company: "Linode LLC",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 107,
        name: "OVHcloud",
        website: "ovhcloud.com",
        description: "European cloud provider with data centers worldwide.",
        category: "hosting",
        company: "OVH SAS",
        country: "fr",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 108,
        name: "Hetzner",
        website: "hetzner.com",
        description: "German hosting provider with competitive pricing and good performance.",
        category: "hosting",
        company: "Hetzner Online GmbH",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 109,
        name: "AWS",
        website: "aws.amazon.com",
        description: "Amazon Web Services - comprehensive cloud computing platform.",
        category: "hosting",
        company: "Amazon Web Services",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 110,
        name: "Google Cloud",
        website: "cloud.google.com",
        description: "Google Cloud Platform with advanced AI and machine learning services.",
        category: "hosting",
        company: "Google LLC",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 111,
        name: "Microsoft Azure",
        website: "azure.microsoft.com",
        description: "Microsoft's cloud computing platform with enterprise features.",
        category: "hosting",
        company: "Microsoft Corporation",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 112,
        name: "Scaleway",
        website: "scaleway.com",
        description: "European cloud provider with competitive pricing and GDPR compliance.",
        category: "hosting",
        company: "Scaleway",
        country: "fr",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 113,
        name: "Contabo",
        website: "contabo.com",
        description: "German hosting provider with high-performance servers at competitive prices.",
        category: "hosting",
        company: "Contabo GmbH",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 114,
        name: "Netcup",
        website: "netcup.de",
        description: "German hosting provider with excellent performance and competitive pricing.",
        category: "hosting",
        company: "Netcup GmbH",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 115,
        name: "Leaseweb",
        website: "leaseweb.com",
        description: "Global hosting provider with data centers worldwide.",
        category: "hosting",
        company: "Leaseweb",
        country: "nl",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 116,
        name: "Server4You",
        website: "server4you.de",
        description: "German hosting provider with dedicated servers and VPS solutions.",
        category: "hosting",
        company: "Server4You",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 117,
        name: "Strato",
        website: "strato.de",
        description: "German hosting provider with comprehensive web hosting solutions.",
        category: "hosting",
        company: "Strato AG",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 118,
        name: "1&1 IONOS",
        website: "ionos.com",
        description: "German hosting provider with domain registration and hosting services.",
        category: "hosting",
        company: "1&1 IONOS",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 119,
        name: "HostEurope",
        website: "hosteurope.de",
        description: "German hosting provider with cloud and dedicated server solutions.",
        category: "hosting",
        company: "HostEurope",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 120,
        name: "All-Inkl",
        website: "all-inkl.com",
        description: "German hosting provider with comprehensive web hosting packages.",
        category: "hosting",
        company: "All-Inkl",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 121,
        name: "WebhostOne",
        website: "webhostone.com",
        description: "Hosting provider with shared hosting and VPS solutions.",
        category: "hosting",
        company: "WebhostOne",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 122,
        name: "A2 Hosting",
        website: "a2hosting.com",
        description: "High-performance hosting with SSD storage and developer-friendly features.",
        category: "hosting",
        company: "A2 Hosting",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 123,
        name: "InMotion Hosting",
        website: "inmotionhosting.com",
        description: "Business-focused hosting with excellent customer support.",
        category: "hosting",
        company: "InMotion Hosting",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 124,
        name: "SiteGround",
        website: "siteground.com",
        description: "WordPress-optimized hosting with excellent performance and support.",
        category: "hosting",
        company: "SiteGround",
        country: "bg",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 125,
        name: "Bluehost",
        website: "bluehost.com",
        description: "Popular hosting provider with WordPress integration and competitive pricing.",
        category: "hosting",
        company: "Bluehost",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 126,
        name: "HostGator",
        website: "hostgator.com",
        description: "Web hosting provider with shared, VPS, and dedicated hosting solutions.",
        category: "hosting",
        company: "HostGator",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 127,
        name: "DreamHost",
        website: "dreamhost.com",
        description: "Web hosting provider with domain registration and WHOIS privacy.",
        category: "hosting",
        company: "DreamHost",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 128,
        name: "GreenGeeks",
        website: "greengeeks.com",
        description: "Eco-friendly hosting provider with renewable energy-powered data centers.",
        category: "hosting",
        company: "GreenGeeks",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 129,
        name: "Liquid Web",
        website: "liquidweb.com",
        description: "Premium hosting provider with managed hosting and dedicated servers.",
        category: "hosting",
        company: "Liquid Web",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 130,
        name: "WP Engine",
        website: "wpengine.com",
        description: "WordPress-optimized hosting with managed WordPress services.",
        category: "hosting",
        company: "WP Engine",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },

    // DOMAIN REGISTRARS (From offshore.cat scraper + tld-list.com)
    {
        id: 201,
        name: "Cloudflare",
        website: "cloudflare.com",
        description: "CDN and domain registrar with WHOIS privacy and competitive pricing.",
        category: "domains",
        company: "Cloudflare Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 202,
        name: "Gandi.net",
        website: "gandi.net",
        description: "European domain registrar with privacy protection and SSL certificates.",
        category: "domains",
        company: "Gandi SAS",
        country: "fr",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bitcoin"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 203,
        name: "Dynadot",
        website: "dynadot.com",
        description: "Domain registrar with WHOIS privacy and multiple payment options.",
        category: "domains",
        company: "Dynadot LLC",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Check"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 204,
        name: "Dotology",
        website: "dotology.com",
        description: "Domain registrar accepting cryptocurrency payments.",
        category: "domains",
        company: "Dotology Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Bitcoin", "Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 205,
        name: "NameCheap",
        website: "namecheap.com",
        description: "Popular domain registrar and web hosting provider with competitive pricing and good customer support.",
        category: "domains",
        company: "NameCheap Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bitcoin"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 206,
        name: "GoDaddy",
        website: "godaddy.com",
        description: "Domain registrar and web hosting provider with extensive service offerings.",
        category: "domains",
        company: "GoDaddy Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 207,
        name: "Hexonet",
        website: "hexonet.net",
        description: "European domain registrar with extensive TLD support.",
        category: "domains",
        company: "HEXONET GmbH",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 208,
        name: "EuroDNS",
        website: "eurodns.com",
        description: "European domain registrar with SSL certificates and email services.",
        category: "domains",
        company: "EuroDNS S.A.",
        country: "lu",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 209,
        name: "101domain",
        website: "101domain.com",
        description: "Domain registrar with extensive TLD support and competitive pricing.",
        category: "domains",
        company: "101domain Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 210,
        name: "AEserver",
        website: "aeserver.com",
        description: "Domain registrar with hosting services and competitive pricing.",
        category: "domains",
        company: "AEserver",
        country: "unknown",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "unverified",
        lastChange: "2025-01-29"
    },
    {
        id: 211,
        name: "Above.com",
        website: "above.com",
        description: "Domain registrar with WHOIS privacy and bank transfer options.",
        category: "domains",
        company: "Above.com",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Bank Transfer", "Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 212,
        name: "Alibaba Cloud",
        website: "alibabacloud.com",
        description: "Cloud provider with domain registration services and GDPR compliance.",
        category: "domains",
        company: "Alibaba Cloud",
        country: "cn",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 213,
        name: "Amazon Route 53",
        website: "aws.amazon.com/route53",
        description: "AWS domain registration with email forwarding and WHOIS privacy.",
        category: "domains",
        company: "Amazon Web Services",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 214,
        name: "BigRock",
        website: "bigrock.com",
        description: "Domain registrar with email accounts and forwarding services.",
        category: "domains",
        company: "BigRock",
        country: "in",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Bank Transfer", "Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 215,
        name: "Blacknight",
        website: "blacknight.com",
        description: "Irish domain registrar with DNS services and multiple payment options.",
        category: "domains",
        company: "Blacknight",
        country: "ie",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Check", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 216,
        name: "CanSpace",
        website: "canspace.ca",
        description: "Canadian domain registrar with hosting services.",
        category: "domains",
        company: "CanSpace",
        country: "ca",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card"],
        status: "unverified",
        lastChange: "2025-01-29"
    },
    {
        id: 217,
        name: "Cosmotown",
        website: "cosmotown.com",
        description: "Domain registrar with WHOIS privacy protection.",
        category: "domains",
        company: "Cosmotown",
        country: "unknown",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 218,
        name: "Crazy Domains",
        website: "crazydomains.com",
        description: "Domain registrar with hosting and multiple payment methods.",
        category: "domains",
        company: "Crazy Domains",
        country: "au",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Neteller", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 219,
        name: "Directnic",
        website: "directnic.com",
        description: "Domain registrar with DNS services and competitive pricing.",
        category: "domains",
        company: "Directnic",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 220,
        name: "Domain.com",
        website: "domain.com",
        description: "Domain registrar with email forwarding and hosting services.",
        category: "domains",
        company: "Domain.com",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 221,
        name: "Domgate",
        website: "domgate.com",
        description: "Domain registrar with extensive TLD support.",
        category: "domains",
        company: "Domgate",
        country: "unknown",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Bank Transfer", "Credit Card", "PayPal"],
        status: "unverified",
        lastChange: "2025-01-29"
    },
    {
        id: 222,
        name: "DreamHost",
        website: "dreamhost.com",
        description: "Web hosting provider with domain registration and WHOIS privacy.",
        category: "domains",
        company: "DreamHost",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 223,
        name: "Easyspace",
        website: "easyspace.com",
        description: "UK-based domain registrar with hosting services.",
        category: "domains",
        company: "Easyspace",
        country: "gb",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 224,
        name: "Hello.co",
        website: "hello.co",
        description: "Domain registrar with 50 email accounts included.",
        category: "domains",
        company: "Hello.co",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 225,
        name: "Hostcab",
        website: "hostcab.com",
        description: "Domain registrar with extensive payment options including crypto.",
        category: "domains",
        company: "Hostcab",
        country: "unknown",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Bank Transfer", "Bitcoin", "Credit Card", "Payeer", "PayPal", "WebMoney", "Yandex.Money"],
        status: "unverified",
        lastChange: "2025-01-29"
    },
    {
        id: 226,
        name: "Hostinger",
        website: "hostinger.com",
        description: "Web hosting provider with domain registration and WHOIS privacy.",
        category: "domains",
        company: "Hostinger International",
        country: "lt",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Bitcoin", "Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 227,
        name: "Internet.bs",
        website: "internet.bs",
        description: "Bahamas-based domain registrar with privacy protection.",
        category: "domains",
        company: "Internet.bs",
        country: "bs",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 228,
        name: "Joker.com",
        website: "joker.com",
        description: "Swiss domain registrar with privacy protection and competitive pricing.",
        category: "domains",
        company: "Joker.com",
        country: "ch",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 229,
        name: "Key-Systems",
        website: "key-systems.net",
        description: "German domain registrar with extensive TLD support.",
        category: "domains",
        company: "Key-Systems GmbH",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 230,
        name: "Marcaria",
        website: "marcaria.com",
        description: "International domain registrar with trademark protection services.",
        category: "domains",
        company: "Marcaria",
        country: "ar",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 231,
        name: "MarkMonitor",
        website: "markmonitor.com",
        description: "Enterprise domain management with brand protection services.",
        category: "domains",
        company: "MarkMonitor",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 232,
        name: "Moniker",
        website: "moniker.com",
        description: "Domain registrar with privacy protection and competitive pricing.",
        category: "domains",
        company: "Moniker",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 233,
        name: "Netim",
        website: "netim.com",
        description: "French domain registrar with hosting and email services.",
        category: "domains",
        company: "Netim",
        country: "fr",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 234,
        name: "Network Solutions",
        website: "networksolutions.com",
        description: "One of the oldest domain registrars with comprehensive services.",
        category: "domains",
        company: "Network Solutions",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 235,
        name: "OpenSRS",
        website: "opensrs.com",
        description: "Domain registrar for resellers and hosting providers.",
        category: "domains",
        company: "OpenSRS",
        country: "ca",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 236,
        name: "OVH",
        website: "ovh.com",
        description: "French hosting provider with domain registration services.",
        category: "domains",
        company: "OVH SAS",
        country: "fr",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 237,
        name: "Porkbun",
        website: "porkbun.com",
        description: "Domain registrar with competitive pricing and privacy protection.",
        category: "domains",
        company: "Porkbun",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 238,
        name: "Register.com",
        website: "register.com",
        description: "Domain registrar with hosting and email services.",
        category: "domains",
        company: "Register.com",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 239,
        name: "Sedo",
        website: "sedo.com",
        description: "Domain marketplace and registrar with parking services.",
        category: "domains",
        company: "Sedo",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 240,
        name: "Squarespace",
        website: "squarespace.com",
        description: "Website builder with domain registration and hosting.",
        category: "domains",
        company: "Squarespace",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 241,
        name: "Tucows",
        website: "tucows.com",
        description: "Canadian domain registrar with hosting and email services.",
        category: "domains",
        company: "Tucows",
        country: "ca",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 242,
        name: "Uniregistry",
        website: "uniregistry.com",
        description: "Domain registrar with new gTLD support and competitive pricing.",
        category: "domains",
        company: "Uniregistry",
        country: "ky",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 243,
        name: "Web.com",
        website: "web.com",
        description: "Web hosting and domain registration with website builder.",
        category: "domains",
        company: "Web.com",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 244,
        name: "Wix",
        website: "wix.com",
        description: "Website builder with domain registration and hosting services.",
        category: "domains",
        company: "Wix",
        country: "il",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 245,
        name: "MyNymBox",
        website: "mynymbox.io",
        description: "Privacy-focused domain registrar with anonymous registration",
        category: "domains",
        company: "MyNymBox",
        country: "unknown",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Crypto", "Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },

    // VPN SERVICES (From offshore.cat scraper)
    {
        id: 301,
        name: "Mullvad",
        website: "mullvad.net",
        description: "Swedish VPN with no logging and anonymous payment options",
        category: "vpn",
        company: "Mullvad VPN",
        country: "se",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 302,
        name: "ProtonVPN",
        website: "protonvpn.com",
        description: "Swiss VPN with strong encryption and no logs policy",
        category: "vpn",
        company: "Proton Technologies AG",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 303,
        name: "NordVPN",
        website: "nordvpn.com",
        description: "Panama-based VPN with extensive server network",
        category: "vpn",
        company: "NordVPN",
        country: "pa",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 304,
        name: "ExpressVPN",
        website: "expressvpn.com",
        description: "British Virgin Islands VPN with high-speed servers",
        category: "vpn",
        company: "ExpressVPN",
        country: "vg",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 305,
        name: "Surfshark",
        website: "surfshark.com",
        description: "British Virgin Islands VPN with unlimited devices",
        category: "vpn",
        company: "Surfshark",
        country: "vg",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 306,
        name: "Private Internet Access",
        website: "privateinternetaccess.com",
        description: "US-based VPN with strong privacy features",
        category: "vpn",
        company: "Private Internet Access",
        country: "us",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 307,
        name: "CyberGhost",
        website: "cyberghostvpn.com",
        description: "Romanian VPN with user-friendly interface",
        category: "vpn",
        company: "CyberGhost",
        country: "ro",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 308,
        name: "Windscribe",
        website: "windscribe.com",
        description: "Canadian VPN with generous free tier",
        category: "vpn",
        company: "Windscribe",
        country: "ca",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 309,
        name: "TunnelBear",
        website: "tunnelbear.com",
        description: "Canadian VPN with simple interface and good security",
        category: "vpn",
        company: "TunnelBear",
        country: "ca",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 310,
        name: "VyprVPN",
        website: "vyprvpn.com",
        description: "Swiss VPN with proprietary Chameleon protocol",
        category: "vpn",
        company: "VyprVPN",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 311,
        name: "IPVanish",
        website: "ipvanish.com",
        description: "US-based VPN with unlimited bandwidth",
        category: "vpn",
        company: "IPVanish",
        country: "us",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 312,
        name: "Hotspot Shield",
        website: "hotspotshield.com",
        description: "US-based VPN with proprietary Catapult Hydra protocol",
        category: "vpn",
        company: "Hotspot Shield",
        country: "us",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 313,
        name: "Hide.me",
        website: "hide.me",
        description: "Malaysian VPN with strong encryption and no logs",
        category: "vpn",
        company: "Hide.me",
        country: "my",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 314,
        name: "Perfect Privacy",
        website: "perfect-privacy.com",
        description: "Swiss VPN with advanced privacy features",
        category: "vpn",
        company: "Perfect Privacy",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 315,
        name: "AirVPN",
        website: "airvpn.org",
        description: "Italian VPN with strong focus on privacy and security",
        category: "vpn",
        company: "AirVPN",
        country: "it",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 316,
        name: "IVPN",
        website: "ivpn.net",
        description: "Gibraltar-based VPN with strong privacy protection",
        category: "vpn",
        company: "IVPN",
        country: "gi",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 317,
        name: "OVPN",
        website: "ovpn.com",
        description: "Swedish VPN with focus on privacy and transparency",
        category: "vpn",
        company: "OVPN",
        country: "se",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 318,
        name: "AzireVPN",
        website: "azirevpn.com",
        description: "Swedish VPN with WireGuard support",
        category: "vpn",
        company: "AzireVPN",
        country: "se",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 319,
        name: "VPN.ac",
        website: "vpn.ac",
        description: "Romanian VPN with academic focus and strong security",
        category: "vpn",
        company: "VPN.ac",
        country: "ro",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 320,
        name: "Trust.Zone",
        website: "trust.zone",
        description: "Seychelles-based VPN with no logs policy",
        category: "vpn",
        company: "Trust.Zone",
        country: "sc",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },

    // MESSENGERS (From offshore.cat scraper)
    {
        id: 401,
        name: "Telegram",
        website: "telegram.org",
        description: "Secure messaging app with end-to-end encryption and cloud storage.",
        category: "messengers",
        company: "Telegram FZ LLC",
        country: "ae",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Premium"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 402,
        name: "Session",
        website: "getsession.org",
        description: "Decentralized messenger with no central servers and metadata protection.",
        category: "messengers",
        company: "Session Foundation",
        country: "au",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "No",
        paymentMethods: ["Free", "Donations"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 403,
        name: "Element",
        website: "element.io",
        description: "Secure messaging and collaboration platform based on Matrix protocol.",
        category: "messengers",
        company: "Element AG",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Premium"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 404,
        name: "Wire",
        website: "wire.com",
        description: "Secure messaging with end-to-end encryption and file sharing.",
        category: "messengers",
        company: "Wire Swiss GmbH",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Premium"],
        status: "verified",
        lastChange: "2025-01-29"
    },

    // CRYPTO EXCHANGES (From offshore.cat scraper)
    {
        id: 501,
        name: "Binance",
        website: "binance.com",
        description: "World's largest cryptocurrency exchange by trading volume.",
        category: "crypto",
        company: "Binance Holdings Ltd",
        country: "ky",
        logPolicy: "Requires KYC",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Bank Transfer", "Crypto"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 502,
        name: "Coinbase",
        website: "coinbase.com",
        description: "Popular cryptocurrency exchange and wallet service.",
        category: "crypto",
        company: "Coinbase Global Inc",
        country: "us",
        logPolicy: "Requires KYC",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Bank Transfer", "Crypto"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 503,
        name: "Kraken",
        website: "kraken.com",
        description: "Cryptocurrency exchange with advanced trading features and security.",
        category: "crypto",
        company: "Payward Inc",
        country: "us",
        logPolicy: "Requires KYC",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Bank Transfer", "Crypto"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 504,
        name: "KuCoin",
        website: "kucoin.com",
        description: "Cryptocurrency exchange with extensive altcoin support.",
        category: "crypto",
        company: "KuCoin Exchange",
        country: "sg",
        logPolicy: "Requires KYC",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Bank Transfer", "Crypto"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 505,
        name: "Bybit",
        website: "bybit.com",
        description: "Cryptocurrency derivatives exchange with advanced trading tools.",
        category: "crypto",
        company: "Bybit Exchange",
        country: "sg",
        logPolicy: "Requires KYC",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Bank Transfer", "Crypto"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },

    // EMAIL SERVICES (From offshore.cat scraper)
    {
        id: 401,
        name: "Cock.li",
        website: "cock.li",
        description: "Email service owned by Vincent Canfield",
        category: "email",
        company: "Cock.li",
        country: "cw",
        logPolicy: "Requires email confirmation",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },

    {
        id: 403,
        name: "ProtonMail",
        website: "protonmail.com",
        description: "Swiss-based encrypted email service with end-to-end encryption",
        category: "email",
        company: "Proton Technologies AG",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 404,
        name: "Tutanota",
        website: "tutanota.com",
        description: "German encrypted email service with zero-knowledge encryption",
        category: "email",
        company: "Tutanota",
        country: "de",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 405,
        name: "Mailfence",
        website: "mailfence.com",
        description: "Belgian encrypted email service with digital signatures",
        category: "email",
        company: "Mailfence",
        country: "be",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 406,
        name: "Posteo",
        website: "posteo.de",
        description: "German green email provider with strong privacy protection",
        category: "email",
        company: "Posteo",
        country: "de",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Bank Transfer"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 407,
        name: "StartMail",
        website: "startmail.com",
        description: "Dutch encrypted email service with custom domains",
        category: "email",
        company: "StartMail",
        country: "nl",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 408,
        name: "Kolab Now",
        website: "kolabnow.com",
        description: "Swiss-based secure email and collaboration platform",
        category: "email",
        company: "Kolab Systems",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 409,
        name: "Runbox",
        website: "runbox.com",
        description: "Norwegian email provider with strong privacy protection",
        category: "email",
        company: "Runbox",
        country: "no",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 410,
        name: "FastMail",
        website: "fastmail.com",
        description: "Australian email service with excellent features and privacy",
        category: "email",
        company: "FastMail",
        country: "au",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 411,
        name: "Hushmail",
        website: "hushmail.com",
        description: "Canadian encrypted email service for healthcare and legal",
        category: "email",
        company: "Hushmail",
        country: "ca",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 412,
        name: "Zoho Mail",
        website: "zoho.com/mail",
        description: "Indian business email service with custom domains",
        category: "email",
        company: "Zoho Corporation",
        country: "in",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 413,
        name: "Yandex Mail",
        website: "mail.yandex.com",
        description: "Russian email service with generous storage",
        category: "email",
        company: "Yandex",
        country: "ru",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 414,
        name: "GMX",
        website: "gmx.com",
        description: "German email provider with large storage capacity",
        category: "email",
        company: "GMX",
        country: "de",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 415,
        name: "Outlook",
        website: "outlook.com",
        description: "Microsoft's email service with Office integration",
        category: "email",
        company: "Microsoft Corporation",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 416,
        name: "Gmail",
        website: "gmail.com",
        description: "Google's email service with advanced features",
        category: "email",
        company: "Google LLC",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },

    // CDN/WAF SERVICES (From offshore.cat scraper)
    {
        id: 701,
        name: "Fastly",
        website: "fastly.com",
        description: "Edge cloud platform with real-time analytics and security.",
        category: "cdn",
        company: "Fastly Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Enterprise"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 702,
        name: "Akamai",
        website: "akamai.com",
        description: "Global CDN and cybersecurity services with extensive network.",
        category: "cdn",
        company: "Akamai Technologies",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Enterprise"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 703,
        name: "Bunny.net",
        website: "bunny.net",
        description: "High-performance CDN with global edge locations and competitive pricing.",
        category: "cdn",
        company: "BunnyWay d.o.o.",
        country: "si",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },

    // UPLOADERS (From offshore.cat scraper)
    {
        id: 801,
        name: "MegaUpload",
        website: "megaupload.com",
        description: "File hosting and sharing service with large storage capacity.",
        category: "uploaders",
        company: "Mega Limited",
        country: "nz",
        logPolicy: "Requires email confirmation",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "unverified",
        lastChange: "2025-01-29"
    },
    {
        id: 802,
        name: "Mega",
        website: "mega.nz",
        description: "Secure cloud storage with end-to-end encryption.",
        category: "uploaders",
        company: "Mega Limited",
        country: "nz",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 803,
        name: "Tresorit",
        website: "tresorit.com",
        description: "Swiss-based secure cloud storage with end-to-end encryption.",
        category: "uploaders",
        company: "Tresorit AG",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 804,
        name: "pCloud",
        website: "pcloud.com",
        description: "Cloud storage with client-side encryption and lifetime plans.",
        category: "uploaders",
        company: "pCloud AG",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 805,
        name: "Sync.com",
        website: "sync.com",
        description: "Canadian cloud storage with zero-knowledge encryption.",
        category: "uploaders",
        company: "Sync.com Inc",
        country: "ca",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },

    // PRIVACY PRODUCTS
    {
        id: 901,
        name: "Google Pixel (Jailbroken)",
        website: "pixel.google.com",
        description: "Privacy-focused Android phone with custom ROM and de-Googled firmware.",
        category: "products",
        company: "Google LLC",
        country: "us",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Crypto", "Cash"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    {
        id: 902,
        name: "iPhone (Jailbroken)",
        website: "apple.com",
        description: "iOS device with jailbreak for privacy enhancements and custom tweaks.",
        category: "products",
        company: "Apple Inc",
        country: "us",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Crypto", "Cash"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    {
        id: 903,
        name: "PinePhone",
        website: "pine64.org",
        description: "Linux-based smartphone with privacy-focused operating system.",
        category: "products",
        company: "PINE64",
        country: "cn",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 904,
        name: "Fairphone",
        website: "fairphone.com",
        description: "Ethical smartphone with modular design and privacy features.",
        category: "products",
        company: "Fairphone",
        country: "nl",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Crypto"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 905,
        name: "Samsung (De-Googled)",
        website: "samsung.com",
        description: "Samsung devices with custom ROM and privacy-focused modifications.",
        category: "products",
        company: "Samsung Electronics",
        country: "kr",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Crypto", "Cash"],
        status: "premium",
        lastChange: "2025-01-29"
    },
    // MESSENGERS (From offshore.cat scraper)
    {
        id: 501,
        name: "Signal",
        website: "signal.org",
        description: "Open-source encrypted messaging with end-to-end encryption",
        category: "messengers",
        company: "Signal Foundation",
        country: "us",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Donations"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 502,
        name: "Telegram",
        website: "telegram.org",
        description: "Cloud-based messaging with secret chats and channels",
        category: "messengers",
        company: "Telegram FZ LLC",
        country: "ae",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Donations"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 503,
        name: "WhatsApp",
        website: "whatsapp.com",
        description: "Facebook-owned messaging with end-to-end encryption",
        category: "messengers",
        company: "Meta Platforms",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 504,
        name: "Wickr",
        website: "wickr.com",
        description: "Secure messaging with self-destructing messages",
        category: "messengers",
        company: "Wickr",
        country: "us",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 505,
        name: "Threema",
        website: "threema.ch",
        description: "Swiss secure messaging with no phone number required",
        category: "messengers",
        company: "Threema",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "PayPal"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 506,
        name: "Wire",
        website: "wire.com",
        description: "Swiss secure messaging with enterprise features",
        category: "messengers",
        company: "Wire",
        country: "ch",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 507,
        name: "Element",
        website: "element.io",
        description: "Open-source Matrix-based messaging platform",
        category: "messengers",
        company: "Element",
        country: "gb",
        logPolicy: "No logs",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 508,
        name: "Session",
        website: "getsession.org",
        description: "Decentralized messaging with no central servers",
        category: "messengers",
        company: "Session",
        country: "unknown",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "No",
        paymentMethods: ["Free"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 509,
        name: "Briar",
        website: "briarproject.org",
        description: "Peer-to-peer messaging with no internet required",
        category: "messengers",
        company: "Briar Project",
        country: "unknown",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "No",
        paymentMethods: ["Free"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 510,
        name: "Jami",
        website: "jami.net",
        description: "Decentralized communication platform",
        category: "messengers",
        company: "Jami",
        country: "ca",
        logPolicy: "No logs",
        dmca: "Ignored",
        ownsServers: "No",
        paymentMethods: ["Free"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 511,
        name: "Discord",
        website: "discord.com",
        description: "Gaming-focused chat platform with voice channels",
        category: "messengers",
        company: "Discord Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 512,
        name: "Slack",
        website: "slack.com",
        description: "Business communication platform with integrations",
        category: "messengers",
        company: "Slack Technologies",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 513,
        name: "Microsoft Teams",
        website: "teams.microsoft.com",
        description: "Microsoft's business communication platform",
        category: "messengers",
        company: "Microsoft Corporation",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Credit Card", "Enterprise"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 514,
        name: "Skype",
        website: "skype.com",
        description: "Microsoft's video calling and messaging platform",
        category: "messengers",
        company: "Microsoft Corporation",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 515,
        name: "Viber",
        website: "viber.com",
        description: "Rakuten's messaging and calling platform",
        category: "messengers",
        company: "Rakuten Viber",
        country: "jp",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 516,
        name: "Line",
        website: "line.me",
        description: "Japanese messaging platform with stickers and games",
        category: "messengers",
        company: "LINE Corporation",
        country: "jp",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 517,
        name: "WeChat",
        website: "wechat.com",
        description: "Chinese messaging and social media platform",
        category: "messengers",
        company: "Tencent",
        country: "cn",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 518,
        name: "KakaoTalk",
        website: "kakao.com",
        description: "South Korean messaging platform",
        category: "messengers",
        company: "Kakao",
        country: "kr",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    },
    {
        id: 519,
        name: "Snapchat",
        website: "snapchat.com",
        description: "Ephemeral messaging and social media platform",
        category: "messengers",
        company: "Snap Inc",
        country: "us",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "capitalist",
        lastChange: "2025-01-29"
    },
    {
        id: 520,
        name: "Kik",
        website: "kik.com",
        description: "Canadian messaging platform with anonymity features",
        category: "messengers",
        company: "Kik Interactive",
        country: "ca",
        logPolicy: "Requires email confirmation",
        dmca: "Enforced",
        ownsServers: "Yes",
        paymentMethods: ["Free", "Credit Card"],
        status: "verified",
        lastChange: "2025-01-29"
    }
];

// DOM elements
const servicesTableBody = document.getElementById('servicesTableBody');
const searchInput = document.getElementById('searchInput');
const filterButtons = document.querySelectorAll('.filter-btn');
const navLinks = document.querySelectorAll('.nav-link');

// Current filter state
let currentFilter = 'all';
let currentCategory = 'all';
let searchTerm = '';

// Initialize the application
function init() {
    renderServices();
    setupEventListeners();
}

// Setup event listeners
function setupEventListeners() {
    // Search functionality
    searchInput.addEventListener('input', (e) => {
        searchTerm = e.target.value.toLowerCase();
        renderServices();
    });

    // Filter buttons
    filterButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            filterButtons.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            currentFilter = btn.dataset.filter;
            renderServices();
        });
    });

    // Navigation
    navLinks.forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            navLinks.forEach(l => l.classList.remove('active'));
            link.classList.add('active');
            currentCategory = link.dataset.category;
            renderServices();
        });
    });
}

// Format date
function formatDate(dateString) {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
    });
}

// Get status display
function getStatusDisplay(status) {
    switch(status) {
        case 'verified':
            return '<i class="fas fa-check"></i> verified';
        case 'capitalist':
            return '<i class="fas fa-coins"></i> capitalist';
        case 'unverified':
            return '<i class="fas fa-question"></i> unverified';
        case 'trash':
            return '<i class="fas fa-times"></i> trash';
        case 'premium':
            return '<i class="fas fa-star"></i> premium';
        default:
            return '<i class="fas fa-question"></i> unknown';
    }
}

// Get country flag with local file path
function getCountryFlag(country) {
    if (country === 'unknown') {
        return '<span class="country-flag unknown">?</span>';
    }
    return `<span class="country-flag" style="background-image: url('flags/${country}.png');"></span>`;
}

// Render services
function renderServices() {
    let filteredServices = servicesData.filter(service => {
        // Category filter
        if (currentCategory !== 'all' && service.category !== currentCategory) {
            return false;
        }

        // Status filter
        if (currentFilter !== 'all' && service.status !== currentFilter) {
            return false;
        }

        // Search filter
        if (searchTerm) {
            const searchFields = [
                service.name,
                service.description,
                service.website
            ].join(' ').toLowerCase();
            
            if (!searchFields.includes(searchTerm)) {
                return false;
            }
        }

        return true;
    });

    if (filteredServices.length === 0) {
        servicesTableBody.innerHTML = `
            <tr>
                <td colspan="10" style="text-align: center; padding: 40px; color: #666;">
                    no services found
                </td>
            </tr>
        `;
        return;
    }

    servicesTableBody.innerHTML = filteredServices.map(service => {
        return `
            <tr>
                <td>${service.name}</td>
                <td><a href="https://${service.website}" target="_blank" class="website-link">${service.website}</a></td>
                <td>${service.description}</td>
                <td>${getCountryFlag(service.country)}</td>
                <td>${service.logPolicy}</td>
                <td>${service.dmca}</td>
                <td>${service.ownsServers}</td>
                <td>
                    <div class="payment-methods">
                        ${service.paymentMethods.map(method => 
                            `<span class="payment-method">${method}</span>`
                        ).join('')}
                    </div>
                </td>
                <td><span class="status ${service.status}">${getStatusDisplay(service.status)}</span></td>
                <td>${formatDate(service.lastChange)}</td>
            </tr>
        `;
    }).join('');
}

// Initialize when DOM is loaded
document.addEventListener('DOMContentLoaded', init); 